### ISSUE TITLE
problem while running multi gpt

### ISSUE THREAD

**Issue by CapAxel** [cjbarre/multi-gpt#1]
Hello ! 
i have a problem with multi-gpt.
I paid my OpenIA account and tried to debug with the command.

Error:
  Traceback (most recent call last):
  File "C:\Users\axelf\Multigpt\Multi-GPT\autogpt\logs.py", line 250, in print_assistant_thoughts
    logger.typewriter_log(f"{active_agent.ai_name.upper()}:", Fore.YELLOW, f"{assistant_thoughts_speak}")
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'ai_name'

How could i fix that?

**Comment by cjbarre** [comment]
Hello there, 

I think you're in the wrong place. This project is a work in progress interface to OpenAI GPT and other LLMs via the Clojure programming language.

I think you might be looking for another project related for AutoGPT by the looks of your error there.
